#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /{reactRouting}
    controller: App\Controller\MainController::index

api_recipes:
    path: api/recipes
    controller: App\Controller\ApiController::getRecipes
    