#index:
#    path: /
#    controller: App\Controller\DefaultController::index

test_form:
    path: test/form
    controller: App\Controller\TestController::formIngredients

api_data:
    path: api/data
    controller: App\Controller\ApiController::setData
    