#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index

api_data:
    path: api/data
    controller: App\Controller\ApiController::setData
    